from graph import *
from kernel import *
import traceback
from svm import SVM
import seaborn as sns
import matplotlib.pyplot as plt
db = Database()
#lab, nolab = db.load_db("ENZYMES")
#s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="sylv_eq_kernel")
#dic=s.cross_val_score(3)
#print(dic)
#s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="conj_grad_kernel",k=10)
#dic2=s.cross_val_score(3)
#print(dic2)
#s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="fixed_point_kernel",k=50)
#dic3=s.cross_val_score(3)
#print(dic3)
#s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="spec_decomp_kernel")
#dic4=s.cross_val_score(3)
#print(dic4)
lab, nolab = db.load_db("MUTAG")
s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="raw_kernel")
dic1=s.cross_val_score(3)
print(dic1)
s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="inv_kernel")
dic2=s.cross_val_score(3)
print(dic2)
s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="sylv_eq_kernel")
dic5=s.cross_val_score(3)
print(dic5)
s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="conj_grad_kernel",k=10)
dic6=s.cross_val_score(3)
print(dic6)
s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="fixed_point_kernel",k=50)
dic7=s.cross_val_score(3)
print(dic7)
s = SVM(db=nolab, ratio_split=0.7, lbd=0.05, kernel="spec_decomp_kernel")
dic8=s.cross_val_score(3)
print(dic8)
with open("results","w") as f:
    f.write("ENZYMES\n")
    f.write(str(dic))
    f.write("\n")
    f.write(str(dic2))
    f.write("\n")
    f.write("\n")
    f.write("PROTEINS\n")    
    f.write(str(dic5))
    f.write("\n")
    f.write(str(dic6))
    f.write("\n")
    f.write(str(dic7))
    f.write("\n")
    f.write(str(dic8))
    f.write("\n")
